spring:
  mongodb:
    database: ${MONGO_NAME:foreign_bot}
    host: ${MONGO_WAY:mongo}
    port: ${MONGO_PORT:27017}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${CORE_PORT:8081}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}
